sever:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  #Khi tao entity tren java se khong tu generate tren db
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


api:
  prefix: api/v1